### ISSUE TITLE
Guy thinks he's funny cuz he's spamming my test webhook

### ISSUE THREAD

**Issue by ghost** [mega145/Discord_token_grabber#2]
skid nice webhook c:

**Comment by MegaTheTeapot** [comment]
1 do i look like i care
2 I'm not using that anyway

**Comment by MegaTheTeapot** [comment]
Only forks on ur GH nice

**Comment by MegaTheTeapot** [comment]
Also looking into that test.py and then running a while loop of requests is kinda skiddy ngl

**Comment by MegaTheTeapot** [comment]
> 1 do i look like i care 2 I'm not using that anyway.  
<br>
Literally made it for the README

**Comment by mega145** [comment]
Got bored?
Cuz it seems ur script stopped working.
Or maybe that's because an error? 🤔

**Comment by MegaTheTeapot** [comment]
This is getting boring tbh 🥱.

**Comment by mega145** [comment]
@uixzz such a brick wall of you

**Comment by MegaTheTeapot** [comment]
@uixzz ur such a brick wall

**Comment by ghost** [comment]
> Only forks on ur GH nice

lol ur dumb u fr think ima jus post my tools onto github when most are paid + i dont use github only to find dumb skids lol

**Comment by MegaTheTeapot** [comment]
> > Only forks on ur GH nice
> 
> lol ur dumb u fr think ima jus post my tools onto github when most are paid + i dont use github only to find dumb skids lol

I'm just saying what i can see.
